name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'pass the project_id'
        required: true

jobs:
  test_manual_workflow:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This is my ${{ github.event.inputs.project_id }}"
